version: "3.9"

services:  
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DB_VENDOR: mssql
      DB_USER: sa
      DB_PASSWORD: SqlServer2019!
      DB_ADDR: mssql
      DB_DATABASE: Keycloak
    command:
      - start-dev 
      # - --import-realm
    restart: unless-stopped
    depends_on:
      #- mssql
      #- mssqlscripts